<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="demoTestng.DemoGroup" tests="8" time="0.018" ignored="0" failures="1" timestamp="07 Feb 2022 11:16:06 GMT" skipped="5" hostname="HEY-JOY" errors="0">
  <testcase name="tc_f1" time="0.013" classname="demoTestng.DemoGroup"/>
  <testcase name="tc_s1" time="0.000" classname="demoTestng.DemoGroup">
    <skipped/>
  </testcase> <!-- tc_s1 -->
  <testcase name="tc_i1" time="0.000" classname="demoTestng.DemoGroup">
    <skipped/>
  </testcase> <!-- tc_i1 -->
  <testcase name="tc_s2" time="0.000" classname="demoTestng.DemoGroup">
    <skipped/>
  </testcase> <!-- tc_s2 -->
  <testcase name="tc_f2" time="0.003" classname="demoTestng.DemoGroup">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at demoTestng.DemoGroup.tc_f2(DemoGroup.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- tc_f2 -->
  <testcase name="tc_i3" time="0.000" classname="demoTestng.DemoGroup">
    <skipped/>
  </testcase> <!-- tc_i3 -->
  <testcase name="tc_i2" time="0.000" classname="demoTestng.DemoGroup">
    <skipped/>
  </testcase> <!-- tc_i2 -->
  <testcase name="tc_f3" time="0.002" classname="demoTestng.DemoGroup"/>
</testsuite> <!-- demoTestng.DemoGroup -->
